#!/usr/bin/env bash
# Installs nginx
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo 'Hello World!' > /etc/nginx/html/index.html
printf %s "server {
    listen  80 default_server;
    listen  [::]:80 default_server;
    root    /etc/nginx/html;
    index   index.html;
    location /redirect_me {
        return 301 http://beesonj.tech/;
    }
}
" > /etc/nginx/sites-available/default
service nginx restart
