#!/usr/bin/env bash
# displays infinite loop of To infinity and beyond with 2 second sleep between iterations and I am invincible!!! while receiving SIGTERM signal

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
