#!/usr/bin/env bash
# loop that prints Best School 10 times and adds hi on the ninth line

count=0
while [ $count -lt 10 ];
do
	if [ $count -eq 8 ]
   then
echo -e "Best School\nHi"
else
echo "Best School"
fi
count=$((count +1))
done
