#!/usr/bin/env bash
# while loop that displays Best School and specific numbers
i=1
while [ $i -le 10 ]
do
	if [ $i = 4 ]
	then
		echo "bad luck"
	elif [ $i = 8 ]
	then
		echo "good luck"
	else echo "Best School"
	fi
	i=$(( i + 1 ))
done
