#!/usr/bin/env bash
# script that displays content of current directory, in a list format, where only the part of the name after the first dash is displayed.

for file in *
do
	echo "$file" | cut -d- -f2
done

