#!/usr/bin/env bash
# install nginx on remote server
# Create a hello world html file
apt-get update
apt-get upgrade -y
apt-get install -y nginx
# Create a hello world html file
mkdir /etc/nginx/html
touch /etc/nginx/html/index_temp.html /etc/nginx/html/404.html
echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
# configurate nginx to listen on port 80
printf %s "server {
    listen  80 default_server;
    listen  [::]:80 default_server;
    root    /etc/nginx/html;
    index   index.html;
    add_header X-Served-By $HOSTNAME;
    location /redirect_me {
        return 301 http://beesonj.tech/;
    }
    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
